### ISSUE TITLE
ESM version?

### ISSUE THREAD

**Issue by rotsee** [buhrmi/vue-sync#11]
Such a nice tool! Any plans on making this an ESM module?

**Comment by buhrmi** [comment]
I'm afraid there won't be an ESM version as we've switched to [Svelte](https://svelte.dev) and this is unmainted

**Comment by rotsee** [comment]
> I'm afraid there won't be an ESM version as we've switched to [Svelte](https://svelte.dev) and this is unmainted

Ok, thank you for replying!
