### ISSUE TITLE
Question: Syncing URL w/JSON object and data model

### ISSUE THREAD

**Issue by eklem** [buhrmi/vue-sync#2]
Hi @buhrmi !
I'm trying to wrap my head around routing, and think that vue-sync may be the right option for me.
I'm making a search frontend and would like part of my URL to be a JSON object, since it's the way the backend defines state.

Is it possible to sync i.e. `/search?q={"query":{"AND":{"Varenavn":["champagne"]}},"pageSize":"3"}` with the object `q` in the data model?

**Comment by buhrmi** [comment]
Thanks for the feature suggestion. Currently, it only supports syncing simple strings, not objects. But your suggestion makes complete sense. Will add this feature in the next day or two.

**Comment by eklem** [comment]
Thats great! I'll test it. Vue-router wasn't fitting my use-case since the state is an actual object =)

**Comment by buhrmi** [comment]
I've released vue-sync 2.0.3 which adds support for nested data models syncing in the URL.

Now you can do this to sync your query object with the URL
    
    Vue.use(VueSync)
    locationSync = VueSync.locationStrategy()
    
    new Vue({
      sync: {
        q: locationSync('q')
      }
    })

**Comment by eklem** [comment]
Cool, thank you so much!
