### ISSUE TITLE
Question: How to use in browser?

### ISSUE THREAD

**Issue by eklem** [buhrmi/vue-sync#3]
Hi again @buhrmi !
I'm trying to use this in a browser setting, and tried this in my html:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset=utf-8>
    <link rel="stylesheet" media="all" href="https://cdn.rawgit.com/cutestrap/cutestrap/master/dist/css/cutestrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.4/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/1.0.3/vue-resource.js"></script>
    <script src="https://rawgit.com/buhrmi/vue-sync/master/index.js"></script>
    <title>test</title>
  </head>
<body>
```

But that fails, and you have only the require method in your example. So how do I use this in a browser setting?

**Comment by buhrmi** [comment]
You're right. I missed a function when porting it to Vue 2.0 ... I fixed it and it should work fine now. I've put an example here: https://q.stefan.co.jp/_preview_site/mognLQRRadjmtoGyt/vue-sync-test

**Comment by eklem** [comment]
Cool!  Thanks for quick replies and good help!
