### ISSUE TITLE
No longer can use noHistory for locationStrategy

### ISSUE THREAD

**Issue by deltragon** [buhrmi/vue-sync#4]
Hello,
The latest update broke support for noHistory (using replace instead of push) for the URL, which I was using in a project.
```js
sync: { myParam: VueSync.locationStrategy()("param", true) },
```
The new API no longer allows this, however:
```js
url: { myParam: "param" },
```
Proposal for a new API that supports passing arguments:
```js
url: {
    // not a breaking change, supports both the current api
    myParam: "param",
    // and the new extended api
    myOtherParam: { 
        param: "param2",
        noHistory: true,
    },
},
```
Regards

**Comment by buhrmi** [comment]
Right, sorry for the breaking change without incrementing the correct semver version. the proposed api looks good.

**Comment by deltragon** [comment]
I will create a Pull Request with the change, if it's alright.

**Comment by buhrmi** [comment]
wow thanks but I've already added the feature.

**Comment by deltragon** [comment]
Thanks!

**Comment by deltragon** [comment]
On a side note: i was reading the code cause i was interested in how you solved it, and I found a typo: you spelled "immediate" wrong in the call to vm.$watch on line 28
also, the other vm.$watch (line 187) call takes an option "sync" which isn't documented (https://vuejs.org/v2/api/#vm-watch), I'm assuming this wasn't intentional either?

**Comment by buhrmi** [comment]
thanks for the report. 

the `sync` option in line 187 is intentional. it's an undocumented feature that instructs the reactivity engine to call all the dependent functions as soon as the reactive value is changed instead of doing it in $nextTick

**Comment by deltragon** [comment]
Huh, that's good to know
