### ISSUE TITLE
do you have a working example anywhere? 

### ISSUE THREAD

**Issue by jdwallace12** [buhrmi/vue-sync#6]
Hey this looks like something I could really use for a project any chance you have a working example.  I am looking to use html slider inputs to populate a url with parameters.  I need to make a shareable link out of all the values, which means the sliders would be able to set their values based on the url parameters.  Any tips would be greatly appreciated.  Want to do something like this:
```
<section class="section">
    <div id="app" class="container">
    <input type="range" min="0" step="1" max="100" v-model="locations">
    <p> Locations: {{ locations }}</p>
    </div>
  </section>
  <script>

    var vm = new Vue({
      el: '#app',
      data: {
        // starting values
        locations: 0
      },
      url: {
        locations: 'locations'
      },
      computed: {
        getLocations: function() {
          var locations = this.locations;
        }
      }

    });
  </script>
```

**Comment by buhrmi** [comment]
yes it should work just fine.

Working example here: https://github.com/buhrmi/vue-sync/blob/master/test/test.html

**Comment by jdwallace12** [comment]
thanks so much! works perfectly.
